### PR TITLE
Add support for Django 1.10

### PR DESCRIPTION
**Pull request by devbis**
Reworked commit, keeping existing support for previous Django version

### CODE REVIEW

**Comment by Suor** [comment]
Why not:
```python
getattr(model, '_deferred') or model.get_deferred_fields()
```
Should be both shorter and faster.

**Comment by devbis** [comment]
`get_deferred_fields` appeared only in version 1.8, so on pre-1.8 this will raise exception if `_deferred` is False

**Comment by Suor** [comment]
Sorry, I meant:
```python
getattr(model, '_deferred', False) or model.get_deferred_fields()
```

**Comment by devbis** [comment]
if `getattr(model, '_deferred', False)` is False this will call missing method `get_deferred_fields`, raising AttributeError

**Comment by Suor** [comment]
Was trying to get rid of extra call and exception handling. I should have used `hasattr()` obviously.

Still your solution doesn't feel right -  any `AttributeError` inside `model.get_deferred_fields()` will be wrongfully intercepted. So I suggest testing `hasattr(model, 'get_deferred_fields')` instead.

**Comment by alexallah** [comment]
Or try _deferred first and execute get_deferred_fields only on AttributeError:

```python
def model_is_deferred(model):
    try:
         return model._deferred
    except AttributeError:
        return bool(model.get_deferred_fields())
```

**Comment by otistamp** [comment]
with this patch applied I get `maximum recursion depth exceeded` in `/usr/src/app/src/django-pickling/django_pickling.py in model_is_deferred, line 14`

**Comment by Suor** [comment]
Please no stylistic changes. I value code history more.

And I believe approach to version is wrong. You are now saving it to every pickle and original intention was to dump it. So the right fix would be to trigger Django to not warn about version.

**Comment by devbis** [comment]
I'm sorry, these changesets were not intended to appear in pull request. I close it.

**Pull request closed without merging**
